### ISSUE TITLE
2024 Plan / TODO List

### ISSUE THREAD

**Issue by KevinMX** [KevinMX/Railgun#6]
Project Railgun 经过了几个月的休眠，将在 2024 迎来更新：

- [ ] Actions CI Workflow 重构
- [ ] MT7981 设备重新加入支持，设备切换回 MTK SDK¹
- [ ] MT7621 设备保留 MTK SDK 版本构建²
- [ ] 完善现有设备支持，config 模板更新
   - [ ] 维持原有目标：尽可能在不同设备上提供统一体验
   - [ ] 硬路由提供 AP / 全功能两个版本？
- [ ] 若基础设施就位³，将提供在线 Firmware Selector / Builder

Note:
⁰预计将使使用 https://github.com/jlumbroso/free-disk-space 等项目。
¹主线开源驱动版本 / ImmortalWrt 在我自己的 MT7981 设备上，多 AP 场景出现了众多问题，现阶段回退到厂商 SDK 版本可能仍是更好的选择。
²仍推荐用户选用 ImmortalWrt / OpenWrt 主线开源驱动版本。
³说人话：缺机器。
